name: Create GitHub Release

on:
  # Run on demand
  workflow_dispatch:

  # Run on push to main when .bumpversion.cfg version is updated
  push:
    branches:
      - main
      - master
    paths:
      - .bumpversion.cfg

jobs:
  release:
    uses: plus3it/actions-workflows/.github/workflows/release.yml@c9c3d1193bd64bc2a9def11605608a98a3164d96
    secrets:
      release-token: ${{ secrets.GH_RELEASES_TOKEN }}
